name: Snowflake CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Git repository
      uses: actions/checkout@v2

    - name: Install SnowSQL CLI
      run: |
        sudo curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.17-linux_x86_64.bash
        sudo bash snowsql-1.2.17-linux_x86_64.bash

    - name: Deploy Snowflake objects
      env:
        SNOWSQL_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
        SNOWSQL_USER: ${{ secrets.SF_USERNAME }}
        SNOWSQL_PASSWORD: ${{ secrets.SF_PASSWORD }}
        SF_ROLE: ${{ secrets.SF_ROLE }}
        SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
        SF_DATABASE: ${{ secrets.SF_DATABASE }}
      run: |
        snowsql -a $SNOWSQL_ACCOUNT -u $SNOWSQL_USER -p $SNOWSQL_PASSWORD -f ./dbscripts/*.sql
